services:
  - type: web_service
    name: backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker backend.api.main:app

  - type: static_site
    name: frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: frontend/dist
